### ISSUE TITLE
bin files current?

### ISSUE THREAD

**Issue by dwillmore** [dioannidis/usbasp#1]
The readme.md mentions prebuilt bin files are in bin, but those files seem to be from the original commit and not updated recently.

Are they current?

**Comment by dioannidis** [comment]
I'm not sure but I rebuild them anyway.

Could you please check if they are working for you ?

**Comment by dwillmore** [comment]
None of the .hex files match the hash of the one I generated. Am I comparing it wrong?  Which of the files in bin/firmware should match the default main.hex from /firmware?

**Comment by dioannidis** [comment]
Hi,

> Looking at the commit, you changed the .hex files in firmware/, not in bin/firmware/ Okay. Those don't match my local build, either. Compiler version differences, maybe?

  I'm using Microchip's ( Atmel ) current tool chain ( gcc version 5.4.0 (AVR_8_bit_GNU_Toolchain_3.6.2_1778) ). The firmware's in bin directory I assume that are builded from the original Fischl's code.

  The updated firmware's 1.08 are in firmware directory, main.hex for the atmega8 and m88.hex for the atmega88.

regards,
