### ISSUE TITLE
question: compatibility esp8266

### ISSUE THREAD

**Issue by beckmx** [dioannidis/usbasp#16]
Hello there, I was looking at the code and I was wondering if this can be migrated to esp8266, I have noticed some references to the avr compiler, very few, but if you mind pointing which files would be modified, maybe I can give it a try to port it to the esp. 

Thanks!

**Comment by dioannidis** [comment]
Hi @beckmx ,

> I was looking at the code and I was wondering if this can be migrated to esp8266

  the firmware uses [V-USB](https://github.com/obdev/v-usb), which is an AVR USB library with AVR assembly, so nope. I don't think it can be done.

  If you want to use the ESP8266 module to program AVR MCU's you can take a look at the [ESP8266AVRISP](https://github.com/esp8266/Arduino/tree/master/libraries/ESP8266AVRISP) arduino library .
