### ISSUE TITLE
flashed main.hex, windows happy, avrdude NOT

### ISSUE THREAD

**Issue by mitchjs** [dioannidis/usbasp#3]
it seems

from MASTER

PS D:\Downloads\avrdude-v6.3.1.1-windows> .\avrdude.exe -c usbasp -p m328p -t
avrdude.exe: error: could not find USB device with vid=0x16c0 pid=0x5dc vendor='www.fischl.de' product='USBasp'

but if i do a 

PS D:\Downloads\avrdude-v6.3.1.1-windows> .\avrdude.exe -c usbasp-clone -p m328p -t

its happy

in your fw, did vendor='www.fischl.de' product='USBasp' change?

oh yes, the "www." is missing from vendor

i see you trimmed it off in a commit while back, remember why?
i think it would be better with it

thanks
mitch

**Comment by linxcow** [comment]
I have the same problem : 

C:\winapps\avrdude6.3>avrdude.exe -p m328 -c usbasp
avrdude.exe: error: could not find USB device with vid=0x16c0 pid=0x5dc vendor='www.fischl.de' product='USBasp'

avrdude.exe done.  Thank you.

**Comment by mitchjs** [comment]
@linxcow  you are using the special winusb version of avrdude right?
link: https://github.com/mariusgreuel/avrdude/releases/tag/v6.3.1.1-windows

worked for me, i feel the  vendor "www." should be added back in offically
i compiled a main.hex with it back in, and it works without "-clone"

mitch

**Comment by linxcow** [comment]
No , i didnt know that was a requirement.
I used the 6.3 version of http://download.savannah.gnu.org/releases/avrdude/

**Comment by mitchjs** [comment]
yea.. that build doesnt have support for WINUSB, which is the whole point dioannidis's USBASP
so you dont need to "find signed" drivers... or do that Ziadiag self signed stuff

**Comment by linxcow** [comment]
I understand , but i didnt find any reference on this repository that a special avrdude is required.

**Comment by dioannidis** [comment]
Hi,

> in your fw, did vendor='www.fischl.de' product='USBasp' change?
> 
> oh yes, the "www." is missing from vendor
> 
> i see you trimmed it off in a commit while back, remember why? i think it would be better with it

it was the upstream's ( nerdralph ) decision, to make it run on atmega48 with TPI enabled. 

I  agree that the vendor name change is a problem, that's why I already mentioned it here https://github.com/nerdralph/usbasp/issues/7#issuecomment-814524617 .

**Comment by dioannidis** [comment]
> No , i didnt know that was a requirement. I used the 6.3 version of http://download.savannah.gnu.org/releases/avrdude/

AFAIU the mingw32 avrdude wasn't build with winusb support.  

OTOH, you could use the Arduino's avrdude which has winusb .

**Comment by dioannidis** [comment]
You can find an avrdude windows build with winusb support in the bin\avrdude-winusb directory of the uart branch.
