### ISSUE TITLE
Missing avrdude 7.0 with winusb support

### ISSUE THREAD

**Issue by Bibbbi** [dioannidis/usbasp#9]
Hi @dioannidis,

A new release from AVRDUDE v7.0 for Windows was published.
[https://github.com/mariusgreuel/avrdude/releases/tag/v7.0-windows](url)

Are you planning an update for avrdude 7.0 with winusb support?

**Comment by dioannidis** [comment]
Ho @Bibbbi ,

 I missed the move from savannah to github entirely ( too busy ) ... Sorry ...

 And just saw that they change the avrdude build framework to CMake ( and MSVC for Windows ) . I'll give it a try this weekend but I remember reading in the mail lists that was a plan to add winusb . Did you try it and failed ?

**Comment by dioannidis** [comment]
By the way, as I'll prefer to switch to use the official avrdude I opened an issue there https://github.com/avrdudes/avrdude/issues/968#issue-1239006912 .

**Comment by dioannidis** [comment]
@Bibbbi  for now you can use the avrdude v7 from this https://github.com/mcuee/avrdude/releases/tag/v7.0 .

**Comment by dioannidis** [comment]
@Bibbbi  I changed the avrdude section in the readme adding the avrdude's v7 lack of composite devices support and a link to the mcuee unofficial build .
